###MOSTRAR DISSCOS
GET http://localhost:8080/api/records
###MOSTRAR UN DISCO
GET http://localhost:8080/api/records/c2181edf-041b-0a61-3651-79d671fa3db7
###CREAR UN DISCO
POST http://localhost:8080/api/records
Content-Type: application/json

{
    "recordName": "Presion",
    "duration": 52.9,
    "songs": [
      "Daños",
      "Puede",
      "Limites",
      "Creo",
      "Frente al Río",
      "Sin Paciencia",
      "Día a Día",
      "Sueño",
      "Hoy",
      "9 de Julio",
      "Señales",
      "Desencuentro"
    ],
    "artistName": [
      "Callejero Fino"
    ],
    "rateAverage": 0.5
}
###MODIFICAR UN DISCO (con put)
PUT http://localhost:8080/api/records/71977e61-e777-4a86-9b29-43e7d3ff4709
Content-Type: application/json

{
    "recordName": "Señales",
    "duration": 52.9,
    "songs": [
      "Daños",
      "Puede",
      "Limites",
      "Creo",
      "Frente al Río",
      "Sin Paciencia",
      "Día a Día",
      "Sueño",
      "Hoy",
      "9 de Julio",
      "Señales",
      "Desencuentro"
    ],
    "artistName": [
      "Callejeros"
    ],
    "rateAverage": 5
}
###MODIFICAR UN DISCO (con patch)
PATCH http://localhost:8080/api/records/71977e61-e777-4a86-9b29-43e7d3ff4709
Content-Type: application/json

{
    "recordName": "Señales",
    "artistName": [
        "Callejeros"
    ],
    "rateAverage": 5
}
###BORRAR UN DISCO
DELETE http://localhost:8080/api/records/6a77c14f-4710-45e3-9282-5418487b1a67