###MOSTRAR DISSCOS
GET http://localhost:8080/api/records
###MOSTRAR UN DISCO
GET http://localhost:8080/api/records/653195f80f56bb4795049b21
###CREAR UN DISCO
POST http://localhost:8080/api/records
Content-Type: application/json

{
    "recordName": "Muriendo Lento",
    "duration": 39.23,
    "songs": [
      "Todos Salten",
      "Municiones",
      "Clicqout",
      "Pasamanos",
      "Muriendo Lento",
      "Champaña",
      "Salvaje",
      "Barrio Fino",
      "Otro Empaque",
      "Los Peores",
      "Estrellas del Crimen",
      "Contando Papeles",
      "Pinar",
      "Leona",
      "Lujuria",
      "Cassius Clay",
      "Cuando Baja el Sol"
    ],
    "artistName": [
      "C.R.O",
      "Franky Style"
    ],
    "rateAverage": 4
}
###MODIFICAR UN DISCO (con put)
PUT http://localhost:8080/api/records/653195f80f56bb4795049b21
Content-Type: application/json

{
    "recordName": "Señales",
    "duration": 52.9,
    "songs": [
      "Daños",
      "Puede",
      "Limites",
      "Creo",
      "Frente al Río",
      "Sin Paciencia",
      "Día a Día",
      "Sueño",
      "Hoy",
      "9 de Julio",
      "Señales",
      "Desencuentro"
    ],
    "artistName": [
      "Callejeros"
    ],
    "rateAverage": 5
}
###MODIFICAR UN DISCO (con patch)
PATCH http://localhost:8080/api/records/65222ef5c9ff62e364b8dc9d
Content-Type: application/json

{
    "recordName": "Señales",
    "artistName": [
        "Callejeros"
    ],
    "rateAverage": 5
}
###BORRAR UN DISCO
DELETE http://localhost:8080/api/records/653195f80f56bb4795049b21