###MOSTRAR DISSCOS
GET http://localhost:8080/api/records
###MOSTRAR UN DISCO
GET http://localhost:8080/api/records/65222ef5c9ff62e364b8dc9d
###CREAR UN DISCO
POST http://localhost:8080/api/records
Content-Type: application/json

{
    "recordName": "POST MORTEM",
    "duration": 43.43,
    "songs": [
      "LA PRIMERA",
      "HEGEMONICA",
      "PELOTUDA",
      "DEMIAN",
      "POST MORTEM",
      "BICICLETA",
      "DUO",
      "PISO 13",
      "SIDE",
      "COAHC",
      "BOHEMIAN GROOVE SKIT",
      "OPA",
      "RILLI RILLI",
      "220",
      "TODA LA GENTE",
      "REALITY",
      "ROCKETPOWERS",
      "AMIGOS NUEVOS"
    ],
    "artistName": [
      "Dillom"
    ],
    "rateAverage": 5
}
###MODIFICAR UN DISCO (con put)
PUT http://localhost:8080/api/records/6c14690c-1f8c-4f20-989a-0a624e704c51
Content-Type: application/json

{
    "recordName": "Señales",
    "duration": 52.9,
    "songs": [
      "Daños",
      "Puede",
      "Limites",
      "Creo",
      "Frente al Río",
      "Sin Paciencia",
      "Día a Día",
      "Sueño",
      "Hoy",
      "9 de Julio",
      "Señales",
      "Desencuentro"
    ],
    "artistName": [
      "Callejeros"
    ],
    "rateAverage": 5
}
###MODIFICAR UN DISCO (con patch)
PATCH http://localhost:8080/api/records/65222ef5c9ff62e364b8dc9d
Content-Type: application/json

{
    "recordName": "Señales",
    "artistName": [
        "Callejeros"
    ],
    "rateAverage": 5
}
###BORRAR UN DISCO
DELETE http://localhost:8080/api/records/ac837de4-da3b-4b4e-b374-6db99bcbc6a5