GET http://localhost:8080/api/users
###OBTENER UN USUARIO
GET http://localhost:8080/api/users/6531950457a456dc4cf1e8c4
###CREAR USUARIO
POST http://localhost:8080/api/users
Content-Type: application/json

{        
    "userName": "Santi",
    "email": "santisabb@gmail.com",
    "webLink": "www.el+sabbio.com",
    "totalRecords": 20,
    "favoriteRecords": [
      "nadie sabe que pasara mañana",
      "X100PRE",
      "542"
    ]
}
###ACTUALIZAR INFORMACION (con put)
PUT http://localhost:8080/api/users/6525ff4b6c39f2985680d012
Content-Type: application/json

{
    "userName": "Santi",
    "email": "santisabb@gmail.com",
    "webLink": "www.el+sabbio.com",
    "totalRecords": 20,
    "favoriteRecords": [
      "PRESION",
      "SEÑALES",
      "SED"
    ]
}
###ACTUALIZAR INFORMACION (con put)
PATCH http://localhost:8080/api/users/653195cf0f56bb4795049b20
Content-Type: application/json

{
  "userName": "Santi Sabbio",
  "email": "santisabbio@gmail.com",
  "webLink": "sabb10el+kpo.com"
}
###BORRAR UN USUARIO
DELETE http://localhost:8080/api/users/653195cf0f56bb4795049b20