GET http://localhost:8080/api/users
###CREAR USUARIO
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "userName": "señorx",
    "email": "señorx@gmail.com",
    "webLink": "www.nosoyhjsimpson.com",
    "totalRecords": 12,
    "favoriteRecords":[
        "Otro Dia en el Planeta Tierra",
        "Especial",
        "Viejas Locas"
    ]
}
###OBTENER UN USUARIO
GET http://localhost:8080/api/users/1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed
###MODIFICAR INFO DE UN USUARIO
PATCH  http://localhost:8080/api/users/7917715b-ea41-43ae-82cb-07929e115ce4
Content-Type: application/json

{
    "userName": "Homero Simpson",
    "email": "elhomo@gmail.com",
    "webLink": "www.soyhjsimpson.com"
}
