###MOSTRAR DISSCOS
GET http://localhost:8080/api/records
###MOSTRAR UN DISCO
GET http://localhost:8080/api/records/2f6a716a-f62d-484a-927a-515a928983b6
###CREAR UN DISCO
POST http://localhost:8080/api/records
Content-Type: application/json

{
    "recordName": "Señales",
    "duration": 52.9,
    "songs": [
        "Daños",
        "Puede",
        "Limites",
        "Creo",
        "Frente al Río",
        "Sin Paciencia",
        "Día a Día",
        "Sueño",
        "Hoy",
        "9 de Julio",
        "Señales",
        "Ojala Se Lo Lleve"
    ],
    "artistName": [
        "Callejeros"
    ],
    "rateAverage": 4
}

###MODIFICAR UN DISCO
PATCH http://localhost:8080/api/records/2f6a716a-f62d-484a-927a-515a928983b6
Content-Type: application/json

{
    "songs":[
        "Daños",
      "Puede",
      "Limites",
      "Creo",
      "Frente al Río",
      "Sin Paciencia",
      "Día a Día",
      "Sueño",
      "Hoy",
      "9 de Julio",
      "Señales",
      "Desencuentro"
    ],
    "rateAverage": 5
}
###BORRAR UN DISCO
DELETE http://localhost:8080/api/records/59660cc8-4883-4a7c-89a6-30389282cc68