###MOSTRAR DISSCOS
GET http://localhost:8080/api/records
###MOSTRAR UN DISCO
GET http://localhost:8080/api/records/134138d5-22c2-4eaf-90cd-8e6b3e3a738c
###CREAR UN DISCO
POST http://localhost:8080/api/records
Content-Type: application/json

{
    "recordName": "un disco",
    "duration": 4.20,
    "songs": [
        "un tema",
        "OTRO TEMA",
        "tema de mierda",
        "para probar",
        "outro",
        "por fin",
        "no terminaba mas"
    ],
    "artistName": [
        "un perejil"
    ],
    "rateAverage": -1
}

###MODIFICAR UN DISCO
PUT  http://localhost:8080/api/records/d4c79913-2f1b-4f62-9708-f61b88c07435
Content-Type: application/json

{
        "recordName": "El Jefe del Malianteo(Vol.1)",
    "duration": 41.32,
    "songs": [
      "Intro",
      "Crustaceo Cascarudo",
      "Los unicos",
      "Flow Anti Dea",
      "Yo Me Prendo un Blunt",
      "Me Levanto Borracho",
      "Oye Baby",
      "Medellin",
      "Bien Cabron",
      "50 y 50",
      "Metio en el Mal",
      "Diamantes Baguette"
    ],
    "artistName": [
      "Zaramay",
      "Nahuel The Coach"
    ],
    "rateAverage": 0.5
}
###BORRAR UN DISCO
DELETE http://localhost:8080/api/records/d4c79913-2f1b-4f62-9708-f61b88c07435